### ISSUE TITLE
Motivation and comparison with existing modules

### ISSUE THREAD

**Issue by dandv** [aoi-umi/mongoose-ts#1]
Same question as https://github.com/bangbang93/mongoose-typescript/issues/4

**Comment by aoi-umi** [comment]
i use typegoose before, and i found a bug
https://github.com/szokodiakos/typegoose/issues/182
you can see when they resolve.....

**Comment by aoi-umi** [comment]
and i write some new feature for girdfs

**Comment by dandv** [comment]
> i use typegoose before, and i found a bug
> [szokodiakos/typegoose#182](https://github.com/szokodiakos/typegoose/issues/182)

That's the previous version of typegoose.

Typegoose is now here: https://github.com/typegoose/typegoose

Please search before spending time creating a new package because maybe someone else has done the work and you won't have to :)

**Comment by aoi-umi** [comment]
> > i use typegoose before, and i found a bug
> > [szokodiakos/typegoose#182](https://github.com/szokodiakos/typegoose/issues/182)
> 
> That's the previous version of typegoose.
> 
> Typegoose is now here: https://github.com/typegoose/typegoose
> 
> Please search before spending time creating a new package because maybe someone else has done the work and you won't have to :)

i know,but when i create the package,they had not resolved the bug.
you can see my issue `opened this issue on 22 Aug 2018` and they resolve at `on 8 Aug 2019`
and i had free time to write something, why do you care about this?

**Comment by dandv** [comment]
Because having multiple modules doing the same thing makes it harder for
developers to choose the one that's not appropriate for their project.

Of course having multiple solutions is generally a good thing, as long as
they're not broken subsets of others. Those are just redundant and don't
help anyone.
